apiVersion: v1
kind: Service
metadata:
  name: jaipro-authentication
  namespace: jaipro
spec:
  type: NodePort
  ports:
    - targetPort: 9010
      port: 8080
      nodePort: 31085
  selector:
    service: jaipro-authentication
    type: backend