spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://34.70.86.164:8080/auth/realms/eureka

eureka:
  services:
    eureka-clients:
      keycloak-auth:
        url: http://localhost:8090/eureka/keycloak-auth/v1
        readTimeout: 7000
        writeTimeout: 1000
        connectionTimeout: 300
      resource-server:
        url: http://localhost:8080/eureka/resource-server/v1
        readTimeout: 7000
        writeTimeout: 1000
        connectionTimeout: 300

logging:
  config: classpath:log4j2-dev-spring.xml